import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../app.dart';

class LoanRequestScreen extends StatefulWidget { const LoanRequestScreen({super.key}); @override State<LoanRequestScreen> createState()=>_LoanRequestScreenState(); }
class _LoanRequestScreenState extends State<LoanRequestScreen>{final principal=TextEditingController();final rate=TextEditingController(text:'0.20');final installments=TextEditingController(text:'12');bool loading=false;String? error;
Future<void> submit() async {setState(()=>loading=true);try{await context.read<AppState>().repository.requestLoan(principal:principal.text.trim(),monthlyRate:rate.text.trim(),installments:int.parse(installments.text));if(mounted){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Solicitação enviada para análise.')));context.pop();}}catch(e){if(mounted)setState(()=>error=e.toString());}finally{if(mounted)setState(()=>loading=false);}}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Solicitar empréstimo')),body:ListView(padding:const EdgeInsets.all(20),children:[TextField(controller:principal,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Valor principal',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:rate,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Taxa mensal (ex.: 0.20)',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:installments,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Quantidade de parcelas',border:OutlineInputBorder())),if(error!=null)Padding(padding:const EdgeInsets.only(top:12),child:Text(error!)),const SizedBox(height:20),FilledButton(onPressed:loading?null:submit,child:Text(loading?'Enviando...':'Solicitar'))]));
@override void dispose(){principal.dispose();rate.dispose();installments.dispose();super.dispose();}}
