import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:frcaixinha/models/finance_models.dart';
import 'package:frcaixinha/repositories/app_repository.dart';
import 'package:frcaixinha/screens/payments/pix_payment_screen.dart';
import 'package:frcaixinha/services/api_client.dart';
class FakePixRepository extends AppRepository { FakePixRepository(this.values, {this.receipt}) : super(ApiClient()); final List<Object> values; final PixReceipt? receipt; int calls=0, receiptCalls=0; @override Future<PixPaymentStatusDetails> paymentStatus(int id) async { final value=values[calls < values.length ? calls++ : values.length-1]; if(value is Exception) throw value; return value as PixPaymentStatusDetails; } @override Future<PixReceipt> paymentReceipt(int id) async { receiptCalls++; return receipt!; } }
PixPayment payment({String? qr,String? qrBase64,String? ticket}) => PixPayment(paymentId:1,providerPaymentId:'provider-1',status:'pending',amount:'100.00',qrCode:qr,qrCodeBase64:qrBase64,ticketUrl:ticket);
PixPaymentStatusDetails status(String provider,String obligation) => PixPaymentStatusDetails.fromJson({'payment_id':1,'provider_payment_id':'provider-1','status':provider,'amount':'100.00','obligation_status':obligation});
void main() {
 test('parses payment and receipt',(){final value=status('approved','PARTIAL'); expect(value.isConfirmed,isTrue); expect(value.obligationIsPaid,isFalse); expect(PixReceipt.fromJson({'receipt_version':'v1','receipt_number':'PIX-1','payment':{},'obligation':{},'amounts':{'received':'40.00'},'confirmation':{},'ledger_entries':[]}).amounts.received,'40.00');});
 testWidgets('shows QR copy code and ticket',(tester) async {final repo=FakePixRepository([status('pending','PENDING')]); await tester.pumpWidget(MaterialApp(home:PixPaymentScreen(payment:payment(qr:'copy-me',ticket:'https://ticket'),repository:repo,pollInterval:const Duration(days:1)))); await tester.pump(); expect(find.text('Pix copia e cola'),findsOneWidget); expect(find.text('https://ticket'),findsOneWidget); expect(find.text('Copiar código Pix'),findsOneWidget);});
 testWidgets('confirmed partial invokes callback without paid label',(tester) async {var callbacks=0; final repo=FakePixRepository([status('approved','PARTIAL')]); await tester.pumpWidget(MaterialApp(home:PixPaymentScreen(payment:payment(),repository:repo,pollInterval:const Duration(days:1),onPaymentConfirmed:()=>callbacks++))); await tester.pumpAndSettle(); expect(find.text('Pagamento confirmado. A obrigação pode permanecer parcial.'),findsOneWidget); expect(callbacks,1);});
 testWidgets('loads indicated receipt',(tester) async {final receipt=PixReceipt.fromJson({'receipt_version':'v1','receipt_number':'PIX-1','payment':{},'obligation':{'status_after':'PAID'},'amounts':{'received':'100.00','applied':'100.00'},'confirmation':{},'ledger_entries':[]}); final repo=FakePixRepository([status('approved','PAID')],receipt:receipt); await tester.pumpWidget(MaterialApp(home:PixPaymentScreen(payment:payment(),repository:repo,receiptAvailable:true,pollInterval:const Duration(days:1)))); await tester.pumpAndSettle(); await tester.tap(find.text('Consultar recibo')); await tester.pumpAndSettle(); expect(find.text('Recibo PIX-1'),findsOneWidget);});
 testWidgets('shows retry after failure',(tester) async {final repo=FakePixRepository([Exception('offline'),status('pending','PENDING')]); await tester.pumpWidget(MaterialApp(home:PixPaymentScreen(payment:payment(),repository:repo,pollInterval:const Duration(days:1)))); await tester.pumpAndSettle(); expect(find.text('Tentar novamente'),findsOneWidget); await tester.tap(find.text('Tentar novamente')); await tester.pumpAndSettle(); expect(repo.calls,2);});
 testWidgets('renders QR base64 and polls again', (tester) async { const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLh5wAAAABJRU5ErkJggg=='; final repo=FakePixRepository([status('pending','PENDING')]); await tester.pumpWidget(MaterialApp(home:PixPaymentScreen(payment:payment(qrBase64:png),repository:repo,pollInterval:const Duration(milliseconds:10)))); await tester.pump(); expect(find.byType(Image),findsOneWidget); await tester.pump(const Duration(milliseconds:11)); await tester.pump(); expect(repo.calls,greaterThanOrEqualTo(2)); });
 testWidgets('dispose cancels polling', (tester) async { final repo=FakePixRepository([status('pending','PENDING')]); await tester.pumpWidget(MaterialApp(home:PixPaymentScreen(payment:payment(),repository:repo,pollInterval:const Duration(milliseconds:10)))); await tester.pump(); final calls=repo.calls; await tester.pumpWidget(const SizedBox()); await tester.pump(const Duration(milliseconds:30)); expect(repo.calls,calls); });
 testWidgets('does not show paid message for confirmed partial', (tester) async { final repo=FakePixRepository([status('approved','PARTIAL')]); await tester.pumpWidget(MaterialApp(home:PixPaymentScreen(payment:payment(),repository:repo,pollInterval:const Duration(days:1)))); await tester.pumpAndSettle(); expect(find.text('Pagamento confirmado. A obrigação pode permanecer parcial.'),findsOneWidget); expect(find.text('Pagamento confirmado e obrigação quitada.'),findsNothing); });
}
