import 'package:flutter/material.dart';
import '../../services/api_client.dart';
import '../../services/session.dart';

class ExecutiveRiskExecutionScreen extends StatefulWidget { const ExecutiveRiskExecutionScreen({super.key}); @override State<ExecutiveRiskExecutionScreen> createState()=>_ExecutiveRiskExecutionScreenState(); }
class _ExecutiveRiskExecutionScreenState extends State<ExecutiveRiskExecutionScreen>{ final api=ApiClient(); List<dynamic> items=[]; String? error;
Future<void> load() async { api.token=await Session.getToken(); try{ final d=await api.get('/admin/executive-risk-execution'); items=(d['items'] as List?)??[]; error=null;}catch(e){error=e.toString();} if(mounted)setState((){}); }
Future<void> action(int id,String path,Map<String,dynamic> body) async { try{api.token=await Session.getToken(); await api.post('/admin/executive-risk-execution/$id/$path',body); await load();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));} }
Future<void> complete(int id) async { final e=TextEditingController(),r=TextEditingController(); final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Concluir execução'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:e,maxLines:3,decoration:const InputDecoration(labelText:'Evidência obrigatória')),TextField(controller:r,maxLines:3,decoration:const InputDecoration(labelText:'Resolução obrigatória'))]),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancelar')),ElevatedButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Concluir'))])); if(ok==true)await action(id,'complete',{'evidence_note':e.text,'resolution':r.text}); }
Future<void> verifyItem(int id) async { final n=TextEditingController(); final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Verificar execução'),content:TextField(controller:n,maxLines:3,decoration:const InputDecoration(labelText:'Nota de verificação')),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancelar')),ElevatedButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Validar'))])); if(ok==true)await action(id,'verify',{'note':n.text}); }
@override void initState(){super.initState();load();}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Execução da Decisão'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(12),children:[if(error!=null)Text(error!),...items.map((x)=>Card(child:ListTile(title:Text('Execução #${x['id']} • ${x['status']}'),subtitle:Text('Governança #${x['governance_id']} • responsável: ${x['assigned_to'] ?? '-'}'),trailing: x['status']=='PENDING'?IconButton(icon:const Icon(Icons.playlist_add_check),onPressed:()=>action(x['id'],'assign',{'assigned_to':x['assigned_to'] ?? 1})):x['status']=='ASSIGNED'?IconButton(icon:const Icon(Icons.play_arrow),onPressed:()=>action(x['id'],'start',{})):x['status']=='IN_EXECUTION'?IconButton(icon:const Icon(Icons.task_alt),onPressed:()=>complete(x['id'])):x['status']=='COMPLETED'?IconButton(icon:const Icon(Icons.verified),onPressed:()=>verifyItem(x['id'])):const Icon(Icons.check_circle))))]))); }
