import 'package:flutter/material.dart';
import '../../services/api_client.dart';
import '../../services/session.dart';

class ExecutiveRiskGovernanceScreen extends StatefulWidget { const ExecutiveRiskGovernanceScreen({super.key}); @override State<ExecutiveRiskGovernanceScreen> createState()=>_ExecutiveRiskGovernanceScreenState(); }
class _ExecutiveRiskGovernanceScreenState extends State<ExecutiveRiskGovernanceScreen>{ final api=ApiClient(); List<dynamic> items=[]; String? error; Future<void> load() async { api.token=await Session.getToken(); try{ await api.post('/admin/executive-risk-governance/sync',{}); final d=await api.get('/admin/executive-risk-governance'); items=(d['items'] as List?)??[]; error=null;}catch(e){error=e.toString();} if(mounted)setState((){}); }
Future<void> approve(Map<String,dynamic> x) async { final c=TextEditingController(); final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:Text('Governança #${x['id']}'),content:TextField(controller:c,maxLines:3,decoration:const InputDecoration(labelText:'Condições obrigatórias, se aplicável')),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancelar')),ElevatedButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Aprovar'))])); if(ok!=true)return; try{api.token=await Session.getToken(); await api.post('/admin/executive-risk-governance/${x['id']}/approve',{'conditions':c.text.trim().isEmpty?null:c.text.trim()}); await load();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));} }
Future<void> validateItem(Map<String,dynamic> x) async { try{api.token=await Session.getToken(); await api.post('/admin/executive-risk-governance/${x['id']}/validate',{}); await load();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));} }
@override void initState(){super.initState();load();} @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Governança da Decisão')),body:RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(12),children:[if(error!=null)Text(error!),...items.map((x)=>Card(child:ListTile(title:Text('Decisão #${x['decision_id']} • ${x['status']}'),subtitle:Text('${x['approvals_count']}/${x['required_approvals']} aprovações • validação: ${x['validation_status']}'),trailing: x['status']!='AUTHORIZED'?IconButton(icon:const Icon(Icons.verified_user),onPressed:()=>approve(x)):x['validation_status']!='VALIDATED'?IconButton(icon:const Icon(Icons.fact_check),onPressed:()=>validateItem(x)):const Icon(Icons.check_circle))))]))); }
