import "package:provider/provider.dart";
import 'package:flutter/material.dart';
import '../services/api_client.dart';
import '../services/session.dart';
import 'package:go_router/go_router.dart';
import '../app.dart';
import 'contributions_screen.dart';
import 'admin/admin_dashboard_screen.dart';
import 'notifications_screen.dart';

class HomeScreen extends StatefulWidget { const HomeScreen({super.key}); @override State<HomeScreen> createState()=>_HomeScreenState(); }
class _HomeScreenState extends State<HomeScreen>{ final api=ApiClient(); Map<String,dynamic>? profile,summary; String? error;
 @override void initState(){super.initState();load();}
 Future<void> load() async { api.token=await Session.getToken(); try{final p=await api.get('/members/me'); Map<String,dynamic>? s; if(p['member']!=null)s=await api.get('/contributions/summary'); if(mounted)setState(() { profile=p; summary=s; error=null; });}catch(e){if(mounted)setState(()=>error=e.toString());}}
 Future<void> logout() async { await context.read<AppState>().logout(); if (mounted) context.go('/login'); }
 @override Widget build(BuildContext context){final member=profile?['member']; return Scaffold(appBar:AppBar(title:const Text('FRcaixinha'),actions:[IconButton(onPressed:logout,icon:const Icon(Icons.logout))]),body:RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(20),children:[Text(profile==null?'Carregando...':'Olá, ${profile!['name']}',style:Theme.of(context).textTheme.headlineSmall),if(error!=null)Padding(padding:const EdgeInsets.only(top:16),child:Text(error!)),if(summary!=null)Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Contribuições pagas: R$ ${summary!['paid_total']}'),Text('Pendentes: R$ ${summary!['pending_total']}'),Text('Cotas: ${summary!['quota_units']}')]))),const SizedBox(height:12),if(profile?['role']=='ADMIN')Card(child:ListTile(leading:const Icon(Icons.admin_panel_settings),title:const Text('Painel Administrativo'),subtitle:const Text('Gestão, empréstimos, caixa e auditoria'),trailing:const Icon(Icons.chevron_right),onTap:()=>context.push('/admin'))),if(member!=null)Card(child:ListTile(leading:const Icon(Icons.payments_outlined),title:const Text('Contribuições'),subtitle:const Text('Ver competências e pagar com Pix'),trailing:const Icon(Icons.chevron_right),onTap:()=>context.push('/contributions'))),Card(child:ListTile(leading:const Icon(Icons.request_quote_outlined),title:const Text('Empréstimos'),subtitle:const Text('Solicite e acompanhe suas parcelas.'),trailing:const Icon(Icons.chevron_right),onTap:()=>context.push('/loans'))),Card(child:ListTile(leading:const Icon(Icons.receipt_long_outlined),title:const Text('Extrato'),subtitle:const Text('Consulte os lançamentos da sua conta.'),trailing:const Icon(Icons.chevron_right),onTap:()=>context.push('/statement'))),Card(child:ListTile(leading:const Icon(Icons.account_balance_wallet_outlined),title:const Text('Minha prestação de contas'),subtitle:const Text('Veja apenas os seus dados financeiros.'),trailing:const Icon(Icons.chevron_right),onTap:()=>context.push('/member-portal'))),Card(child: ListTile(leading: const Icon(Icons.notifications_none), title: const Text('Notificações'), subtitle: const Text('Avisos sobre vencimentos e pagamentos.'), trailing: const Icon(Icons.chevron_right), onTap: () => Navigator.push(context, MaterialPageRoute(builder: (_) => const NotificationsScreen())))),Card(child:ListTile(leading:const Icon(Icons.tune),title:const Text('Central de comunicação'),subtitle:const Text('Escolha canais e tipos de aviso.'),trailing:const Icon(Icons.chevron_right),onTap:()=>context.push('/communications'))),Card(child:ListTile(leading:const Icon(Icons.privacy_tip_outlined),title:const Text('Privacidade e LGPD'),subtitle:const Text('Consulte seus dados e solicitações de privacidade.'),trailing:const Icon(Icons.chevron_right),onTap:()=>context.push('/privacy')))])));}

}
