from alembic import op
import sqlalchemy as sa
revision='0049_capa_v072'; down_revision='0048_workflow_incidents_v071'; branch_labels=None; depends_on=None
def upgrade():
    op.create_table('corrective_action_plans',
      sa.Column('id',sa.Integer(),primary_key=True),sa.Column('incident_id',sa.Integer(),sa.ForeignKey('workflow_incidents.id'),nullable=False),sa.Column('status',sa.String(24),nullable=False),sa.Column('owner_id',sa.Integer(),sa.ForeignKey('users.id'),nullable=True),sa.Column('priority',sa.String(16),nullable=False),sa.Column('objective',sa.Text(),nullable=False),sa.Column('root_cause',sa.Text(),nullable=True),sa.Column('effectiveness_criteria',sa.Text(),nullable=True),sa.Column('effectiveness_result',sa.Text(),nullable=True),sa.Column('due_at',sa.DateTime(timezone=True),nullable=True),sa.Column('verified_at',sa.DateTime(timezone=True),nullable=True),sa.Column('closed_at',sa.DateTime(timezone=True),nullable=True),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('incident_id',name='uq_capa_incident'))
    op.create_index('ix_capa_incident','corrective_action_plans',['incident_id'],unique=True); op.create_index('ix_capa_status','corrective_action_plans',['status']); op.create_index('ix_capa_owner','corrective_action_plans',['owner_id']); op.create_index('ix_capa_priority','corrective_action_plans',['priority']); op.create_index('ix_capa_due','corrective_action_plans',['due_at']); op.create_index('ix_capa_updated','corrective_action_plans',['updated_at'])
    op.create_table('corrective_actions',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('capa_id',sa.Integer(),sa.ForeignKey('corrective_action_plans.id'),nullable=False),sa.Column('title',sa.String(200),nullable=False),sa.Column('description',sa.Text(),nullable=True),sa.Column('status',sa.String(24),nullable=False),sa.Column('assigned_to',sa.Integer(),sa.ForeignKey('users.id'),nullable=True),sa.Column('due_at',sa.DateTime(timezone=True),nullable=True),sa.Column('evidence_required',sa.Boolean(),nullable=False),sa.Column('evidence_note',sa.Text(),nullable=True),sa.Column('completed_at',sa.DateTime(timezone=True),nullable=True),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))
    for n,c in [('ix_ca_capa','capa_id'),('ix_ca_status','status'),('ix_ca_assigned','assigned_to'),('ix_ca_due','due_at'),('ix_ca_updated','updated_at')]: op.create_index(n,'corrective_actions',[c])
def downgrade():
    for n in ['ix_ca_updated','ix_ca_due','ix_ca_assigned','ix_ca_status','ix_ca_capa']: op.drop_index(n,table_name='corrective_actions')
    op.drop_table('corrective_actions');
    for n in ['ix_capa_updated','ix_capa_due','ix_capa_priority','ix_capa_owner','ix_capa_status','ix_capa_incident']: op.drop_index(n,table_name='corrective_action_plans')
    op.drop_table('corrective_action_plans')
