"""adiciona principal liquidado com saldo proprio

Revision ID: 005668b9e159
Revises: d04267d34476
Create Date: 2026-09-12 01:34:14.765638
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '005668b9e159'
down_revision: Union[str, Sequence[str], None] = 'd04267d34476'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'loans',
        sa.Column(
            'principal_settled_with_own_balance',
            sa.Numeric(precision=14, scale=2),
            nullable=False,
            server_default=sa.text("0.00"),
        ),
    )
    op.alter_column(
        'loans',
        'principal_settled_with_own_balance',
        server_default=None,
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'principal_settled_with_own_balance')
    # ### end Alembic commands ###
