from alembic import op
import sqlalchemy as sa
revision='0063_continuous_improvement_balancing_v086'; down_revision='0062_continuous_improvement_priority_v085'; branch_labels=None; depends_on=None
def upgrade():
 op.create_table('continuous_improvement_assignment_capacities',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id'),nullable=False),sa.Column('max_active_items',sa.Integer(),nullable=False),sa.Column('max_critical_items',sa.Integer(),nullable=False),sa.Column('enabled',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_ci_assign_cap_user','continuous_improvement_assignment_capacities',['user_id'],unique=True)
 op.create_table('continuous_improvement_assignment_snapshots',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('snapshot_date',sa.Date(),nullable=False),sa.Column('status',sa.String(20),nullable=False),sa.Column('snapshot_json',sa.Text(),nullable=False),sa.Column('snapshot_hash',sa.String(64),nullable=False),sa.Column('generated_by',sa.Integer(),sa.ForeignKey('users.id'),nullable=True),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_ci_assign_date','continuous_improvement_assignment_snapshots',['snapshot_date'],unique=True); op.create_index('ix_ci_assign_status','continuous_improvement_assignment_snapshots',['status']); op.create_index('ix_ci_assign_hash','continuous_improvement_assignment_snapshots',['snapshot_hash'],unique=True)
def downgrade():
 for n in ['ix_ci_assign_hash','ix_ci_assign_status','ix_ci_assign_date']: op.drop_index(n,table_name='continuous_improvement_assignment_snapshots')
 op.drop_table('continuous_improvement_assignment_snapshots'); op.drop_index('ix_ci_assign_cap_user',table_name='continuous_improvement_assignment_capacities'); op.drop_table('continuous_improvement_assignment_capacities')
