from alembic import op
import sqlalchemy as sa
revision='0066_continuous_improvement_evidence_v089'; down_revision='0065_continuous_improvement_execution_v088'; branch_labels=None; depends_on=None
def upgrade():
 op.add_column('continuous_improvement_executions',sa.Column('evidence_manifest_hash',sa.String(64),nullable=True))
 op.create_index('ix_ci_exec_manifest_hash','continuous_improvement_executions',['evidence_manifest_hash'])
 op.create_table('continuous_improvement_execution_evidence_files',
  sa.Column('id',sa.Integer(),primary_key=True),sa.Column('execution_id',sa.Integer(),sa.ForeignKey('continuous_improvement_executions.id'),nullable=False),sa.Column('version',sa.Integer(),nullable=False),sa.Column('original_name',sa.String(255),nullable=False),sa.Column('storage_key',sa.String(240),nullable=False),sa.Column('content_type',sa.String(120),nullable=False),sa.Column('size_bytes',sa.Integer(),nullable=False),sa.Column('sha256',sa.String(64),nullable=False),sa.Column('uploaded_by',sa.Integer(),sa.ForeignKey('users.id'),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('revoked_at',sa.DateTime(timezone=True),nullable=True))
 op.create_index('ix_ci_eef_execution','continuous_improvement_execution_evidence_files',['execution_id']); op.create_index('ix_ci_eef_storage','continuous_improvement_execution_evidence_files',['storage_key'],unique=True); op.create_index('ix_ci_eef_sha','continuous_improvement_execution_evidence_files',['sha256']); op.create_index('ix_ci_eef_uploaded','continuous_improvement_execution_evidence_files',['uploaded_by']); op.create_index('ix_ci_eef_created','continuous_improvement_execution_evidence_files',['created_at'])
 op.create_table('continuous_improvement_evidence_integrity_events',
  sa.Column('id',sa.Integer(),primary_key=True),sa.Column('file_id',sa.Integer(),sa.ForeignKey('continuous_improvement_execution_evidence_files.id'),nullable=False),sa.Column('execution_id',sa.Integer(),sa.ForeignKey('continuous_improvement_executions.id'),nullable=False),sa.Column('event_type',sa.String(20),nullable=False),sa.Column('expected_sha256',sa.String(64),nullable=False),sa.Column('observed_sha256',sa.String(64),nullable=True),sa.Column('status',sa.String(20),nullable=False),sa.Column('actor_id',sa.Integer(),sa.ForeignKey('users.id'),nullable=True),sa.Column('previous_event_hash',sa.String(64),nullable=True),sa.Column('event_hash',sa.String(64),nullable=False),sa.Column('details',sa.Text(),nullable=True),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
 op.create_index('ix_ci_eie_file','continuous_improvement_evidence_integrity_events',['file_id']); op.create_index('ix_ci_eie_execution','continuous_improvement_evidence_integrity_events',['execution_id']); op.create_index('ix_ci_eie_status','continuous_improvement_evidence_integrity_events',['status']); op.create_index('ix_ci_eie_hash','continuous_improvement_evidence_integrity_events',['event_hash'],unique=True); op.create_index('ix_ci_eie_created','continuous_improvement_evidence_integrity_events',['created_at'])
def downgrade():
 for n,t in [('ix_ci_eie_created','continuous_improvement_evidence_integrity_events'),('ix_ci_eie_hash','continuous_improvement_evidence_integrity_events'),('ix_ci_eie_status','continuous_improvement_evidence_integrity_events'),('ix_ci_eie_execution','continuous_improvement_evidence_integrity_events'),('ix_ci_eie_file','continuous_improvement_evidence_integrity_events')]: op.drop_index(n,table_name=t)
 op.drop_table('continuous_improvement_evidence_integrity_events')
 for n in ['ix_ci_eef_created','ix_ci_eef_uploaded','ix_ci_eef_sha','ix_ci_eef_storage','ix_ci_eef_execution']: op.drop_index(n,table_name='continuous_improvement_execution_evidence_files')
 op.drop_table('continuous_improvement_execution_evidence_files'); op.drop_index('ix_ci_exec_manifest_hash',table_name='continuous_improvement_executions'); op.drop_column('continuous_improvement_executions','evidence_manifest_hash')
