"""adiciona conta financeira e lancamentos do membro

Revision ID: d04267d34476
Revises: 8c4f2a1b7d90
Create Date: 2026-09-11 14:17:11.986570
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd04267d34476'
down_revision: Union[str, Sequence[str], None] = '8c4f2a1b7d90'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_financial_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_financial_accounts_member_id'), 'member_financial_accounts', ['member_id'], unique=True)
    op.create_table('member_financial_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['member_financial_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_financial_entries_account_id'), 'member_financial_entries', ['account_id'], unique=False)
    op.create_index(op.f('ix_member_financial_entries_created_at'), 'member_financial_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_member_financial_entries_entry_type'), 'member_financial_entries', ['entry_type'], unique=False)
    op.create_index('ix_member_financial_entries_reference', 'member_financial_entries', ['reference_type', 'reference_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_member_financial_entries_reference', table_name='member_financial_entries')
    op.drop_index(op.f('ix_member_financial_entries_entry_type'), table_name='member_financial_entries')
    op.drop_index(op.f('ix_member_financial_entries_created_at'), table_name='member_financial_entries')
    op.drop_index(op.f('ix_member_financial_entries_account_id'), table_name='member_financial_entries')
    op.drop_table('member_financial_entries')
    op.drop_index(op.f('ix_member_financial_accounts_member_id'), table_name='member_financial_accounts')
    op.drop_table('member_financial_accounts')
    # ### end Alembic commands ###
